import type { Metadata } from "next";
import { ptSansCaption } from "./ui/fonts";
import styles from "@/app/ui/home.module.css";

export const metadata: Metadata = {
  title: {
    template: "Duel Links Replays",
    default: "Duel Links Replays"
  },
  description: "Generated by create next app",
};

// the root component
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={ptSansCaption.className}>{children}</body>
    </html>
  );
}
